# ============================================================
# buildspec.yml
# Fichier de configuration AWS CodeBuild
# Décrit toutes les étapes nécessaires au build et tests
# ============================================================

version: 0.2   # Version utilisée du format buildspec

phases:
  install:      # Phase d'installation des dépendances
    runtime-versions:
      python: 3.8      # Version de Python fournie par CodeBuild
    commands:
      - echo Installing dependencies...     # Log dans la console CodeBuild
      - pip install -r requirements.txt     # Installation des dépendances Python

  pre_build:    # Phase exécutée avant le build
    commands:
      - echo start prebuild and end it      # Ici rien de spécial, juste un message

  build:        # Phase principale du build (tests, compilation, etc.)
    commands:
      - echo Running unit tests with pytest...    # Log explicatif
      - mkdir -p reports                          # Création du dossier de rapport (important)
      - |
        # Exécution des tests avec Pytest
        # --junitxml : génère un rapport XML compatible CodeBuild
        # --tb=short  : résumé des traces d'erreur pour une meilleure lisibilité
        pytest --junitxml=reports/results.xml --tb=short

  post_build:   # Phase exécutée après le build
    commands:
      - echo Build completed successfully.       # Message de fin

artifacts:    # Liste des fichiers sauvegardés à la fin du build
  files:
    - "**/*"               # Inclut tous les fichiers du répertoire du projet
  base-directory: .        # Racine des artifacts

reports:      # Déclaration des rapports de tests (visible dans l'onglet "Reports")
  pytest_reports:
    files:
      - "reports/results.xml"   # Rapport XML généré par pytest
    discard-paths: yes           # Conserve uniquement les fichiers sans les sous-dossiers
